---
title: "Ames Housing EDA and Cleaning"
author: "Joel Bracken"
date: "March 25, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE} 
require(splines)
require(alr4)
require(latex2exp)
require(leaps)
require(effects)
require(glmnet)
require(MASS)
require(fmsb)
require(lars)
require(regclass)
knitr::opts_chunk$set(echo = FALSE)
```



```{r, echo=FALSE,fig.height= 4 ,fig.height= 4 }

setwd("~/PracProj/Ames Housing Data/Ames-Housing-Data") #set working directory
data <- read.csv("AmesHousing.csv",row.names = 1)
attach(data)
par(mfrow=c(2,2))
hist(SalePrice)
qqnorm(SalePrice)
hist(log(SalePrice))        
qqnorm(log(SalePrice))

head(data)

```

```{r}
remove <- c('PID','MS.Zoning', "Street", "Alley", "Land.Contour","Utilites" , "Land.Slope",
            "Condition.1", "Condition.2", "Bldg.type", "Roof.Style", "Roof.Matl", "Bsmt.Cond",
            "BsmtFin.Type.2", "BsmtFin.SF.1", "BsmtFin.SF.2", "Heating", "CentralAir", "Electrical",
            "Low.Qual.Fin.SF", "X1st.Flr.SF", "Kitchen.AbvGr", "Garage.Cars", "Garage.Qual",
            "Garage.Cond")


convert <- c("Mas.Vnr.Type", "Bsmt.Full.Bath", "Bsmt.Half.Bath","Mas.Vnr.Area", "Wood.Deck.SF",
             "Full.Bath", "Half.Bath", "Open.Porch.SF", "X2nd.Flr.SF", "Fireplaces",
             "Enclosed.Porch", "X3Ssn.Porch", "Screen.Porch", "Fence", "Mo.Sold")

# Function to change zeros to No and others to Yes
num.to.bin.cat <- function(list){
  no <- which(list %in% 0)
  yes <- which(!(list %in% 0))
  list[no] <- "No"
  list[yes] <- "Yes"
  return(as.factor(list))
}


# Change continuous variables to categrical 
data$Mas.Vnr <- num.to.bin.cat(data$Mas.Vnr.Area)
data$Two.Floors <- num.to.bin.cat(data$X2nd.Flr.SF)
data$Fireplace <- num.to.bin.cat(data$Fireplaces)
data$Deck <- num.to.bin.cat(data$Wood.Deck.SF)

data$Porch <- data$Open.Porch.SF + data$Enclosed.Porch + data$X3Ssn.Porch + data$Screen.Porch
data$Porch <- num.to.bin.cat(data$Porch)

# Convert categorical variables down to two level
data$Fence <- as.vector(data$Fence)
data$Fence[which(!is.na(data$Fence))] <- "Yes"
data$Fence[which(is.na(data$Fence))] <- "No"
data$Fence <- as.factor(data$Fence)

# Represent bathrooms by single number
data$Bath <- (data$Bsmt.Full.Bath + data$Bsmt.Half.Bath/2)+ (data$Full.Bath + data$Half.Bath/2)


# month to season 
data$Mo.Sold <- data$Mo.Sold +1
data$Mo.Sold[which(data$Mo.Sold %in% 13)] = 1
data$Season <-  ceiling( data$Mo.Sold/3)
seasons <- c("Winter", "Spring", "Summer", "Fall")
seas_int <- c(1,2,3,4)

winter <- c(12,1,2)
spring <- c(3,4,5)
summer <- c(6.7,8)
fall <- c(9,10,11)

for (i in 1:length(seas_int)) {
 row <- which( data$Season %in%  seas_int[i])
 data$Season[row] = seasons[i]
}

#Remove variables
data.clean <- data[,-c( which(names(data) %in% remove),which(names(data) %in% convert))]



```


```{r}
attach(data)  

summary(SalePrice)
hist(SalePrice)
qqnorm(SalePrice)

hist(log(SalePrice))        #It appears the log transform is best
qqnorm(log(SalePrice))

table(MSSubClass)

hist(LotFrontage)

hist(LotArea)

table(Neighborhood)

table(OverallQual)

table(OverallCond)

hist(YearBuilt)

hist(YearRemodAdd)

hist(MasVnrArea)
length(which(MasVnrArea > 0)) ##591 aren't zero

hist(BsmtFinSF1)
length(which(BsmtFinSF1 > 0 )) #993 aren't zero

hist(BsmtFinSF2)
length(which(BsmtFinSF2 > 0 )) #167 aren't zero

hist(BsmtUnfSF)
length(which(BsmtUnfSF > 0 )) #1342 aren't zero

hist(TotalBsmtSF)
length(which(TotalBsmtSF > 0 )) #1423 aren't zero

hist(X1stFlrSF)  #high outliers

hist(X2ndFlrSF)
length(which(X2ndFlrSF > 0 )) #631 aren't zero

hist(LowQualFinSF)
length(which(LowQualFinSF > 0 )) #26 aren't zero

hist(GarageArea)
length(which(GarageArea > 0 )) #1379 aren't zero

hist(GarageYrBlt)

hist(WoodDeckSF)
length(which(WoodDeckSF > 0 )) #699 aren't zero

hist(OpenPorchSF)
length(which(OpenPorchSF > 0 )) #804 aren't zero

hist(EnclosedPorch)
length(which(EnclosedPorch > 0 )) #208 aren't zero

hist(X3SsnPorch)
length(which(X3SsnPorch > 0 )) #24 aren't zero

hist(ScreenPorch)
length(which(ScreenPorch > 0 )) #116 aren't zero

hist(PoolArea)
length(which(PoolArea > 0 )) #7 aren't zero

hist(MiscVal)
length(which(MiscVal > 0 )) #52 aren't zero

hist(MoSold)

hist(YrSold)

table(FullBath)

table(HalfBath)

table(BedroomAbvGr)

table(KitchenAbvGr)

table(TotRmsAbvGrd)

table(Fireplaces)

table(GarageCars)
detach(data)

data <- as.data.frame(data)
tail(sort(data$SalePrice), n= 50) #maybe get rid of highest few points
tail(sort(data$GrLivArea), n = 50) # maybe exclude houses over 4,000 sq ft

data2 <- data[ which(data$GrLivArea < 4000), ]    #remove houses over 4,000 sq ft

tail(sort(data2$SalePrice), n = 50) #got rid of some of our highest values

tail(sort(data2$LotFrontage), n = 50) #maybe get rid of 313 lot (biggest by far)

biglot <- which(data2$LotFrontage > 300)    #removed big lot

data3 <- data2[-biglot,]


tail(sort(data3$GarageArea), n = 50) #some big garages but nothing that is clear outlier

tail(sort(data3$BedroomAbvGr), n = 50) #should probably remove 8 bedroom house

data4 <-data3[-(data3$BedroomAbvGr=8),]

tail(sort(data4$PoolArea), n = 30) #5 houses with pools, could eliminate?

data5 <- data4[-(data4$Utilities == "NoSeWa"),] #removed one house without full utilities
```














```{r}
varsWithNA = names(which(colSums(is.na(data))>0))
#data["MiscFeature"] <- NULL # Missing value in 96.4% of observations
#data["Alley"] <- NULL # Missing value in 93.2% of observations
#data["PoolQC"] <- NULL # Missing value in 99.7% of observations

missingObs = c("MSZoning", "MasVnrType", "Utilities", "Exterior1st", "Exterior2nd", "SaleType")
effZero = c("LotFrontage", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF","GarageCars", "GarageArea", "BsmtFullBath", "BsmtHalfBath")

# Get Effectively Absent category by excluding other categories from varsWithNA
effAbsent = varsWithNA[!varsWithNA %in% missingObs]
effAbsent = effAbsent[!effAbsent %in% effZero]
effAbsent = effAbsent[!effAbsent %in% c("Functional", "GarageYrBlt")]

# Function for replacing NAs in nominal and ordinal variables
replaceNAfactor = function(data.col, factorString){
  char.col <- as.character(data.col)
  char.col[which(is.na(data.col))] <- factorString
  as.factor(char.col)
}
# Replace NAs with None in Effectively Absent category
for (i in 1:ncol(data)){
  if(names(data[i]) %in% effAbsent){
    data[,i] <- replaceNAfactor(data[,i], "None")}
}
# Replace NAs with MissingObs in Missing Observations category
for (i in 1:ncol(data)){
  if(names(data[i]) %in% missingObs){
    data[,i] <- replaceNAfactor(data[,i], "MissingObs")}
}
# Replace NAs with 0 in Effectively Zero category
for (i in 1:ncol(data)){
  if(names(data[i]) %in% effZero)
    data[is.na(data[,i]),i] <- 0
}
# Replace NA with -1 in Missing Numerical Observations category
data$GarageYrBlt[is.na(data$GarageYrBlt)] <- -1

data$Functional <- replaceNAfactor(data$Functional, "Typ")


names(which(colSums(is.na(data))>0))

# Encoding Variables to Correct Types

#data$MSSubClass <- as.factor(data$MSSubClass)

#There are 23 ordinal variables in the dataset. Manually specify the order of factor levels for each variable.
data$LotShape <- ordered(data$LotShape, levels=c("IR3", "IR2", "IR1", "Reg"))
data$Utilities <- ordered(data$Utilities, levels=c("MissingObs", "NoSeWa", "NoSewr", "AllPub"))
data$LandSlope <- ordered(data$LandSlope, levels=c("Gtl", "Mod", "Sev"))
data$OverallQual <- ordered(data$OverallQual)
data$OverallCond <- ordered(data$OverallCond)
data$ExterQual <- ordered(data$ExterQual, levels=c("Po", "Fa", "TA", "Gd", "Ex"))
data$ExterCond <- ordered(data$ExterCond, levels=c("Po", "Fa", "TA", "Gd", "Ex"))
data$BsmtQual <- ordered(data$BsmtQual, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$BsmtCond <- ordered(data$BsmtCond, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$BsmtExposure <- ordered(data$BsmtExposure, levels=c("None", "No", "Mn", "Av", "Gd"))
data$BsmtFinType1 <- ordered(data$BsmtFinType1, levels=c("None", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"))
data$BsmtFinType2 <- ordered(data$BsmtFinType2, levels=c("None", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"))
data$KitchenQual <- ordered(data$KitchenQual, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$Functional <- ordered(data$Functional, levels=c("Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"))
data$FireplaceQu <- ordered(data$FireplaceQu, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$GarageFinish <- ordered(data$GarageFinish, levels=c("None", "Unf", "RFn", "Fin"))
data$GarageQual <- ordered(data$GarageQual, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$GarageCond <- ordered(data$GarageCond, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$PavedDrive <- ordered(data$PavedDrive, levels=c("N", "P", "Y"))
data$Fence <- ordered(data$Fence, levels=c("None", "MnWw", "GdWo", "MnPrv", "GdPrv"))
data$HeatingQC <- ordered(data$HeatingQC, levels=c("None", "Po", "Fa", "TA", "Gd", "Ex"))
data$Electrical <- ordered(data$Electrical, levels=c("None", "Mix", "FuseP", "FuseF", "FuseA", "SBrkr"))
data$PoolQC <- ordered(data$PoolQC, levels=c("None", "Fa", "Gd", "Ex"))
data$Alley <- ordered(data$Alley, levels=c("None", "Grvl", "Pave"))

outliers = numeric()
if (F){
  train.true <- 1:nrow(data.train)
  # Find outliers in train subset
  mod <- lm(SalePrice~.,data=data[train.true,-9]) # Model without Utilities, since they are all the same for train subset
  cooksd <- cooks.distance(mod)
  plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
  abline(h = 8*mean(cooksd, na.rm=T), col="red")  # add cutoff line
  text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>8*mean(cooksd, na.rm=T),names(cooksd),""), col="red")  # add labels
  outliers <- c(524,826,198,692,589,1183,899,1045,1047)
  keepRows <- rep(T,nrow(data))
  keepRows[outliers] <-F
  data <- data[keepRows,]
}



############## BI VARIATE ANALYSIS ############
attach(data)

plot(cbind(data$SalePrice,data[,2:9]))
plot(cbind(data$SalePrice,data[,10:18]))
plot(cbind(data$SalePrice,data[,19:28]))
plot(cbind(data$SalePrice,data[,29:38]))
plot(cbind(data$SalePrice,data[,39:48]))
plot(cbind(data$SalePrice,data[,49:58]))
plot(cbind(data$SalePrice,data[,59:68]))
plot(cbind(data$SalePrice,data[,69:78]))
plot(cbind(data$SalePrice,data[,79:81]))


```




```{r}
set.seed(555) 
trainindex <- sample.int(nrow(data),size = nrow(data)*.80, replace= FALSE) # 80/20 split

mushtrain <- data[trainindex,]
mushtest <- data[-trainindex,]
```

